[package]
cairo-version = "2.4.0"
name = "plaguestark"
version = "0.4.0"

[cairo]
sierra-replace-ids = true

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"

#rpc_url = "http://155.138.223.88:5050"
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x691f741c8fd33d557daced16f586c44f3f64633f4a227485b8cd0a8718d9bd4"

#rpc_url = "https://api.cartridge.gg/x/cubzh/katana"

[dependencies]
starknet = ">=2.2.0"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.4.2" }
